version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_BIND: ${SERVER_BIND}
      DB_URL: ${DB_URL}
      SHADOW_DB_URL: ${SHADOW_DB_URL}
    env_file:
      - .env
    command: |
      sh -c "yarn start"